M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2025-12-26T14:44:29-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-26T14:44:29-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X128.03Y-63.0
X128.03Y-79.0
M30
